ext: json
split: False
class: [ 'data', 'category', 'id' ]
2Dbox:
  center: False
  coord: [ [ 'data', 'bbox', 0 ]
           [ 'data', 'bbox', 1 ],
           [ 'data', 'bbox', 2 ],
           [ 'data', 'bbox', 3 ] ]
3Dbox:
  loc:
    x:
    y:
    z:
  dim:
    length:
    width:
    height:
  rot:
    roll:
    pitch:
    yaw:
extra: [ [ 'data', 'occluded' ],
         [ 'data', 'weather' ],
         [ 'data', 'scene' ] ]