ext: text
split_key: ' '
class: 0
2Dbox:
  coord_type: 'xyxy'
  coord: [4,
          5,
          6,
          7]
3Dbox:
  loc:
    x: 8
    y: 9
    z: 10
  dim:
    length: 11
    width: 12
    height: 13
  rot:
    roll:
    pitch:
    yaw: 14
extra:
  truncated: 1
  occluded: 2
  alpha: 3
file_name: