ext: xml
split_key: [ 'annotation', 'object' ]
class: [ 'name' ]
2Dbox:
  coord_type: 'xyxy'
  coord: [ [ 'bndbox', 'xmin' ],
           [ 'bndbox', 'ymin' ],
           [ 'bndbox', 'xmax' ],
           [ 'bndbox', 'ymax' ] ]
3Dbox:
  loc:
    x:
    y:
    z:
  dim:
    length:
    width:
    height:
  rot:
    roll:
    pitch:
    yaw:
extra:
  'pose': [ 'pose' ]
  'difficult': [ 'difficult' ]
file_name: