ext: json
split_key: [ 'annotations' ]
class: [ 'category_id' ]
2Dbox:
  coord_type: 'xywh'
  coord: [ [ 'bbox', '0' ],
           [ 'bbox', '1' ],
           [ 'bbox', '2' ],
           [ 'bbox', '3' ] ]
3Dbox:
  loc:
    x:
    y:
    z:
  dim:
    length:
    width:
    height:
  rot:
    roll:
    pitch:
    yaw:
extra:
  'iscrowd': [ 'iscrowd' ]
  'image_id': [ 'id' ]
file_name: [ 'image_id' ]