ext: json
anno_key: [ 'data' ]
class: [ 'category', '0', 'id' ]
2Dbox:
  is_center: False
  coord: [ [ 'bbox', '0' ],
           [ 'bbox', '1' ],
           [ 'bbox', '2' ],
           [ 'bbox', '3' ] ]
3Dbox:
  loc:
    x:
    y:
    z:
  dim:
    length:
    width:
    height:
  rot:
    roll:
    pitch:
    yaw:
extra:
  'bbox_id': [ 'bbox_id' ]
  'occluded': [ 'occluded' ]